<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('locations')->insert([
            [
                'name' => 'UIN Aceh',
                'latitude' => 5.579321056411662,
                'longitude' => 95.36737751298347,
                'description' => 'Universitas Islam Negeri Ar-Raniry, disingkat UINAR, merupakan Perguruan Tinggi Keagamaan Islam Negeri yang terletak di Banda Aceh Provinsi Aceh.',
                'address' => 'Lorong Ibnu Sina No.2, Darussalam, Kopelma Darussalam, Kec. Syiah Kuala, Kota Banda Aceh, Aceh 23111',
                'image' => 'assets/img/collab/UIN-ACEH.jpg',
            ],
            [
                'name' => 'BBPPMPV Bidang Bangunan dan Listrik',
                'latitude' => 3.6153038059781344,
                'longitude' => 98.65784550882842,
                'description' => '(BBPPMPV BMTI) merupakan Unit Pelaksana Teknis (UPT) di lingkungan Direktorat Jenderal Pendidikan Vokasi (Ditjen Pendidikan Vokasi), KEMENDIKBUD',
                'address' => 'Geuceu Komp., Kec. Banda Raya, Kota Banda Aceh, Aceh 23239',
                'image' => 'assets/img/collab/BBPPMPV Bidang Bangunan dan Listrik.jpg',
            ],
            [
                'name' => 'Dinas Pendidikan Kepulauan Riau',
                'latitude' => 0.8675679408230308,
                'longitude' => 104.4670059106706,
                'description' => 'Dinas Pendidikan Provinsi Kepulauan Riau adalah instansi pemerintah yang bertanggung jawab atas pengelolaan dan pengembangan sektor pendidikan di Provinsi Kepulauan Riau, Indonesia.',
                'address' => 'Jl. Sultan Mansyur Syah Pulau Dompak Tanjungpinang',
                'image' => 'assets/img/collab/DinasPendidikanKepri.jpg',
            ],
            [
                'name' => 'Dinas Kesehatan Ketapang',
                'latitude' => -1.832678224592698,
                'longitude' => 109.9681093241648,
                'description' => 'Dinas Kesehatan Kabupaten Ketapang merupakan instansi pemerintah daerah yang bertanggung jawab atas pengelolaan dan pengembangan sektor kesehatan di Kabupaten Ketapang',
                'address' => 'JL. Mayjend Jl. DI Panjaitan No.40, Kantor, Kec. Delta Pawan, Kabupaten Ketapang, Kalimantan Barat 78821',
                'image' => 'assets/img/collab/DinasKesehatanKetapang.jpg',
            ],
            [
                'name' => 'Institut Teknologi Kalimantan',
                'latitude' => -1.1496907586267682,
                'longitude' => 116.86217517177666,
                'description' => 'Institut Teknologi Kalimantan adalah perguruan tinggi negeri yang diresmikan pendiriannya pada tanggal 6 Oktober 2014 oleh Presiden RI Susilo Bambang Yudhoyono.',
                'address' => 'Jl. Soekarno Hatta No.KM 15, Karang Joang, Kec. Balikpapan Utara, Kota Balikpapan, Kalimantan Timur 76127',
                'image' => 'assets/img/collab/InstitutTeknologiKalimantan.jpg',
            ],
            [
                'name' => 'Politeknik Tanah Laut',
                'latitude' => -3.752888679663063,
                'longitude' => 114.76686669533662,
                'description' => 'Perguruan Tinggi Negeri di Kabupaten Tanah Laut, yang berdiri pada tanggal 25 September 2009, tetapi baru bisa diresmikan menjadi PTN pada tanggal 2 Februari 2014 dan berdiri sampai dengan sekarang.',
                'address' => 'Jl. Ahmad Yani No.Km.06, Pemuda, Kec. Pelaihari, Kabupaten Tanah Laut, Kalimantan Selatan 70815',
                'image' => 'assets/img/collab/PoliteknikTanahLaut.jpg',
            ],
            [
                'name' => 'Politeknik Negeri Samarinda',
                'latitude' => -0.5287367243049513,
                'longitude' => 117.12394678695843,
                'description' => 'Politeknik Negeri Samarinda atau disingkat Polnes adalah sebuah perguruan tinggi negeri yang terletak di Kota Samarinda, Kalimantan Timur, Indonesia.',
                'address' => 'Jl. Cipto Mangun Kusumo, Sungai Keledang, Kec. Samarinda Seberang, Kota Samarinda, Kalimantan Timur 75242',
                'image' => 'assets/img/collab/PoliteknikNegeriSamarinda.jpg',
            ],
            [
                'name' => 'Universitas Tadulako',
                'latitude' => -0.8361318237503732,
                'longitude' => 119.89366150881963,
                'description' => 'Universitas Tadulako, disingkat UNTAD, adalah Perguruan Tinggi Negeri di Kota Palu, Sulawesi Tengah, Indonesia, sesuai Keppres No. 36 Tahun 1981 Universitas Tadulako berdiri pada tanggal 14 Agustus 1981.',
                'address' => 'Jl. Soekarno Hatta No.KM. 9, Tondo, Kec. Mantikulore, Kota Palu, Sulawesi Tengah 94148',
                'image' => 'assets/img/collab/UniversitasTadulako.jpg',
            ],
            [
                'name' => 'Universitas Mulawarman',
                'latitude' => -0.467442524247122,
                'longitude' => 117.15419571819574,
                'description' => 'Universitas Mulawarman, disingkat Unmul, adalah perguruan tinggi negeri di Samarinda, Kalimantan Timur, Indonesia. Universitas ini berdiri pada tanggal 27 September 1962, sehingga merupakan universitas tertua di Kalimantan Timur',
                'address' => 'Jl. Kuaro, Gn. Kelua, Kec. Samarinda Ulu, Kota Samarinda, Kalimantan Timur 75119',
                'image' => 'assets/img/collab/UniversitasMulawarman.jpg',
            ],
            [
                'name' => 'Politeknik Negeri Balikpapan',
                'latitude' => -1.201798295754245,
                'longitude' => 116.8849048664918,
                'description' => 'Politeknik Negeri Balikpapan disingkat Potekba adalah sebuah perguruan tinggi negeri Vokasi pertama di Balikpapan yang berlokasi persis di tepi Jalan Soekarno Hatta KM 8, Kota Balikpapan, Kalimantan Timur.',
                'address' => 'Jl. Soekarno Hatta No.KM. 8, RW.8, Batu Ampar, Kec. Balikpapan Utara, Kota Balikpapan, Kalimantan Timur 76129',
                'image' => 'assets/img/collab/PoliteknikNegeriBalikpapan.jpg',
            ],
            [
                'name' => 'Universitas Pattimura',
                'latitude' => -3.652886371826334,
                'longitude' => 128.1954795737279,
                'description' => 'Universitas Pattimura atau UNPATTI adalah perguruan tinggi di Negeri Rumahtiga, Kota Ambon yang berdiri pada 8 Agustus 1962. Pada tahun 2023',
                'address' => 'Jl. Ir. M. Putuhena, Poka, Kec. Tlk. Ambon, Kota Ambon, Maluku',
                'image' => 'assets/img/collab/UniversitasPattimura.jpg',
            ],
            [
                'name' => 'UPN Veteran Jawa Timur',
                'latitude' => -7.3330788128903235,
                'longitude' => 112.78842822045081,
                'description' => 'Universitas Pembangunan Nasional "Veteran" Jawa Timur adalah sebuah perguruan tinggi negeri di Indonesia yang berada di Surabaya, Jawa Timur. UPN "Veteran" Jatim berdiri sejak 5 Juli 1959',
                'address' => 'Jl. Rungkut Madya, Gn. Anyar, Kec. Gn. Anyar, Surabaya, Jawa Timur 60294',
                'image' => 'assets/img/collab/UPNVeteranJawaTimur.jpg',
            ],
            [
                'name' => 'BLK Wonogiri',
                'latitude' => -7.818037418963115,
                'longitude' => 110.9821113493396,
                'description' => '(BLK) Wonogiri adalah lembaga pelatihan kerja yang berada di Kabupaten Wonogiri yang menyediakan berbagai program pelatihan keterampilan bagi masyarakat untuk meningkatkan kualitas tenaga kerja dan mempersiapkan mereka untuk memasuki pasar kerja.',
                'address' => 'Jl. Ngadirojo, Ngreco, Ngadirojo Kidul, Kec. Ngadirojo, Kabupaten Wonogiri, Jawa Tengah 57681',
                'image' => 'assets/img/collab/BLKWonogiri.jpg',
            ],
            [
                'name' => 'Universitas Negeri Malang',
                'latitude' => -7.958108179444199,
                'longitude' => 112.61768742081355,
                'description' => 'Universitas Negeri Malang merupakan perguruan tinggi negeri yang terletak di Malang dan Blitar, Jawa Timur, Indonesia. Universitas yang didirikan pada tanggal 18 Oktober 1954.',
                'address' => 'Jl. Cakrawala No.5, Sumbersari, Kec. Lowokwaru, Kota Malang, Jawa Timur 65145',
                'image' => 'assets/img/collab/UniversitasNegeriMalang.jpg',
            ],
            [
                'name' => 'Universitas Negeri Jember',
                'latitude' => -8.164892089894593,
                'longitude' => 113.71647736838868,
                'description' => 'Universitas Jember adalah institusi pendidikan tinggi berkelas dunia yang telah mengikrarkan diri sebagai Kampus Kebangsaan dan Kampus Pancasila.',
                'address' => 'Jl. Kalimantan Tegalboto No.37, Krajan Timur, Sumbersari, Kec. Sumbersari, Kabupaten Jember, Jawa Timur 68121',
                'image' => 'assets/img/collab/UniversitasNegeriJember.jpg',
            ],
            [
                'name' => 'Politeknik Negeri Madiun',
                'latitude' => -7.647482224449454,
                'longitude' => 111.52636326653203,
                'description' => 'Politeknik Negeri Madiun adalah perguruan tinggi negeri yang terdapat di Kota Madiun, Provinsi Jawa Timur, Indonesia. Kampus ini merupakan satu-satunya politeknik negeri di wilayah barat Jawa Timur.',
                'address' => 'Jl. Serayu No.84, Pandean, Taman, Pandean, Kec. Taman, Kota Madiun, Jawa Timur 63133',
                'image' => 'assets/img/collab/PoliteknikNegeriMadiun.jpg',
            ],
            [
                'name' => 'Politeknik Kesehatan Banten',
                'latitude' => -6.124714777213945,
                'longitude' => 106.1998813420086,
                'description' => 'Politeknik Kesehatan Kementerian Kesehatan Banten atau biasa disingkat Poltekkes Banten adalah perguruan tinggi kedinasan yang berada di Kota Serang, Banten dengan penyelenggaraan pendidikan tenaga kesehatan',
                'address' => 'Jl. Syekh Moh. Nawawi Albantani No.12, Banjaragung, Kec. Cipocok Jaya, Kota Serang, Banten 42121',
                'image' => 'assets/img/collab/PoliteknikKesehatanBanten.jpg',
            ],
            [
                'name' => 'Politeknik Kesehatan Semarang',
                'latitude' => -7.054466574764417,
                'longitude' => 110.4283884953617,
                'description' => 'Poltekkes Kemenkes Semarang merupakan perguruan vokasi kesehatan di bawah naungan Direktorat Jendral Tenaga Kesehatan Kementerian Kesehatan RI',
                'address' => 'Jl. Tirto Agung, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268',
                'image' => 'assets/img/collab/PoliteknikKesehatanSemarang.jpg',
            ],
            [
                'name' => 'Politeknik Negeri Cilacap',
                'latitude' => -7.7173314591387,
                'longitude' => 109.01998672235354,
                'description' => 'Politeknik Negeri Cilacap adalah salah satu perguruan tinggi negeri di Jawa Tengah yang berlokasi di Kabupaten Cilacap. Perguruan tinggi ini berdiri pada tahun 2014 dengan dasar hukum Peraturan Menteri Pendidikan dan Kebudayaan RI Nomor 102 Tahun 2014.',
                'address' => 'Jl. Dr. Soetomo No.1, Karangcengis, Sidakaya, Kec. Cilacap Sel., Kabupaten Cilacap, Jawa Tengah 53212',
                'image' => 'assets/img/collab/PoliteknikNegeriCilacap.jpg',
            ],
            [
                'name' => 'Politeknik Negeri Sriwijaya',
                'latitude' => -2.9837959826213245,
                'longitude' => 104.73262760882545,
                'description' => 'Politeknik Negeri Sriwijaya adalah perguruan tinggi negeri yang terdapat di Kota Palembang, Sumatera Selatan, Indonesia. Politeknik Negeri Sriwijaya, dahulunya bernama Politeknik Universitas Sriwijaya secara resmi dibuka pada tanggal 20 September 1982.',
                'address' => 'Jl. Srijaya Negara, Bukit Lama, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan 30128',
                'image' => 'assets/img/collab/PoliteknikNegeriSriwijaya.jpg',
            ],
            [
                'name' => 'Universitas Negeri Sriwijaya',
                'latitude' => -2.855655165455846,
                'longitude' => 104.74170764780824,
                'description' => 'Universitas Sriwijaya adalah sebuah Perguruan Tinggi Negeri di Sumatera Selatan, Indonesia. Universitas Sriwijaya memiliki 10 fakultas yang tersebar pada dua lokasi kampus, yakni di Indralaya, Kabupaten Ogan Ilir dan Bukit Besar, Kota Palembang.',
                'address' => 'Jl. Masjid Al Gazali, Bukit Lama, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan 30128',
                'image' => 'assets/img/collab/UniversitasNegeriSriwijaya.jpg',
            ],
            [
                'name' => 'Dinas PU Ogan Ilir',
                'latitude' => -3.2605445944408373,
                'longitude' => 104.65069120485677,
                'description' => 'Dinas Pekerjaan Umum Kabupaten Ogan Ilir adalah instansi pemerintah yang bertanggung jawab atas pengelolaan dan pelaksanaan proyek-proyek infrastruktur, Sumatera Selatan, Indonesia.',
                'address' => 'Sakatiga Seberang, Kec. Indralaya, Kabupaten Ogan Ilir, Sumatera Selatan 30815',
                'image' => 'assets/img/collab/DinasPekerjaanUmumOganIlir.jpg',
            ],
            [
                'name' => 'Institut Teknologi Sumatera',
                'latitude' => -5.358139292945618,
                'longitude' => 105.31485107527307,
                'description' => 'Institut Teknologi Sumatera (ITERA) merupakan perguruan tinggi negeri baru yang berdiri sejak 6 Oktober 2014 dan berlokasi di Lampung.',
                'address' => 'Jl. Terusan Ryacudu, Way Huwi, Kec. Jati Agung, Kabupaten Lampung Selatan, Lampung 35365',
                'image' => 'assets/img/collab/InstitutTeknologiSumatera.jpg',
            ],
            [
                'name' => 'Kementerian Ketenagakerjaan RI',
                'latitude' => -6.200353992494408,
                'longitude' => 106.83121973325629,
                'description' => 'Kementerian Ketenagakerjaan Republik Indonesia atau Kemnaker adalah kementerian dalam Pemerintah Indonesia yang membidangi urusan ketenagakerjaan.',
                'address' => 'Kuningan Tim., Kecamatan Setiabudi, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12950',
                'image' => 'assets/img/collab/KementerianKetenagakerjaanRI.jpg',
            ],
            [
                'name' => 'BKKBN',
                'latitude' => -6.224724088842559,
                'longitude' => 106.877907498451,
                'description' => 'Badan Kependudukan dan Keluarga Berencana Nasional adalah Lembaga Pemerintah Nonkementerian yang berada di bawah dan bertanggung jawab kepada Presiden melalui Menteri Kesehatan.',
                'address' => 'Jl. Permata No.1 4, RT.4/RW.5, Kb. Pala, Kec. Makasar, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13650',
                'image' => 'assets/img/collab/BKKBN.jpg',
            ],
            [
                'name' => 'Universitas Singaperbangsa Karawang',
                'latitude' => -6.322994531601047,
                'longitude' => 107.30644131069813,
                'description' => 'Universitas Singaperbangsa Karawang adalah perguruan tinggi negeri yang terletak di Karawang, Jawa Barat. Didirikan pada 21 September 2017.',
                'address' => 'Jl. HOS Cokroaminoto, Karangpawitan, Kec. Karawang Bar., Kabupaten Karawang, Jawa Barat 41315',
                'image' => 'assets/img/collab/UniversitasSingaperbangsaKarawang.jpg',
            ],
            [
                'name' => 'Politeknik Penerbangan Indonesia Curug',
                'latitude' => -6.248890262386684,
                'longitude' => 106.74379082043457,
                'description' => 'Politeknik Penerbangan Indonesia Curug adalah perguruan tinggi negeri yang dikelola oleh Kementerian Perhubungan Republik Indonesia. Kampus ini berlokasi di Curug, Banten.',
                'address' => 'Jl. Kolonel Sudirman No.59, Curug, Kec. Curug, Kota Tangerang, Banten 15810',
                'image' => 'assets/img/collab/PoliteknikPenerbanganIndonesiaCurug.jpg',
            ],
            [
                'name' => 'Universitas Muhammadiyah Yogyakarta',
                'latitude' => -7.766590746830098,
                'longitude' => 110.40858688974364,
                'description' => 'Universitas Muhammadiyah Yogyakarta adalah perguruan tinggi swasta yang berada di Yogyakarta, Indonesia, didirikan pada 1 Maret 1981.',
                'address' => 'Jl. Brawijaya, Kasihan, Kec. Kasihan, Kabupaten Bantul, Yogyakarta 55183',
                'image' => 'assets/img/collab/UniversitasMuhammadiyahYogyakarta.jpg',
            ],
            [
                'name' => 'Badan Nasional Penanggulangan Terorisme (BNPT)',
                'latitude' => -6.194540186017878,
                'longitude' => 106.84510541052734,
                'description' => 'Badan Nasional Penanggulangan Terorisme adalah lembaga pemerintah nonkementerian yang berfungsi untuk merumuskan dan melaksanakan kebijakan penanggulangan terorisme di Indonesia.',
                'address' => 'Jl. Tb. Simatupang No. 15, RT.2/RW.10, Cilandak, Kec. Cilandak, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12430',
                'image' => 'assets/img/collab/BadanNasionalPenanggulanganTerorisme.jpg',
            ],
        ]);
    }
}
